name: Deploy to ECR

on: [push]

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: "eu-west-1"
  ECR_REPOSITORY: "mvdb"

jobs:
  # CALL WORKFLOW tag-release
  # tag-release:
  # uses: indigo-tangerine/shared-workflows/.github/workflows/tag-release.yml@main
  # uses: ./.github/workflows/tag-release.yml

  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: [tag-release]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: ${{ inputs.use_v_prefix }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.CICD_AUTOMATION_GITHUB_ACTIONS_ROLE }}
          role-session-name: GithubActions
          mask-aws-account-id: "yes"
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.bump_tag.outputs.tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
